CREATE DATABASE grpctodo;

CREATE TABLE items (
    id VARCHAR(15) UNIQUE NOT NULL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    closed BOOL NOT NULL DEFAULT FALSE
);